title: Swag
author: Sev
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, you! yeah you! Do all of your friends brag about being swaggie. Do you sit and stare at them in awe, wondering why you can't be as yolosawggie as them? Well,our website is the answer to your problems!

# social links
twitter_username: swaggie_yolo
github_username:  yoloswag123

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
